# Generated by Django 6.0.5 on 2026-06-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='total_invested',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
