# Generated by Django 6.0.5 on 2026-06-03 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_wallet_total_invested'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='bonus_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='referral',
            name='bonus_given_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='first_deposit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='first_investment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='has_deposited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='referral',
            name='has_invested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='referralbonus',
            name='bonus_type',
            field=models.CharField(default='referral', max_length=20),
        ),
        migrations.AddField(
            model_name='referralbonus',
            name='referral_ids',
            field=models.TextField(blank=True, help_text='Comma-separated IDs of referrals that triggered this bonus'),
        ),
        migrations.CreateModel(
            name='BalanceAdjustmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('action', models.CharField(choices=[('add', 'Added'), ('subtract', 'Subtracted'), ('bonus', 'Bonus Added'), ('refund', 'Refund')], max_length=20)),
                ('reason', models.TextField()),
                ('previous_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('performed_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_adjustments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
