# Generated by Django 6.0.5 on 2026-06-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_referral_bonus_given_referral_bonus_given_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='requires_password_reset',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='code',
            field=models.CharField(max_length=100),
        ),
    ]
