# Generated by Django 6.0.4 on 2026-05-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_deposit_approved_by_userprofile_is_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEarningsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('users_affected', models.IntegerField(default=0)),
                ('investments_processed', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='investmentproduct',
            name='daily_earnings_rate',
        ),
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=models.CharField(choices=[('pending', '⏳ Pending Approval'), ('approved', '✅ Approved'), ('rejected', '❌ Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='investmentproduct',
            name='level',
            field=models.CharField(choices=[('bronze', 'Bronze Level (KES 520-800)'), ('silver', 'Silver Level (KES 1,000-1,500)'), ('gold', 'Gold Level (KES 2,000-3,000)'), ('platinum', 'Platinum Level (KES 5,000-8,000)'), ('diamond', 'Diamond Level (KES 10,000-12,000)'), ('vip', 'VIP Level (KES 15,000-70,000)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='status',
            field=models.CharField(choices=[('pending', '⏳ Pending'), ('approved', '✅ Approved'), ('rejected', '❌ Rejected')], default='pending', max_length=20),
        ),
    ]
