# Generated by Django 6.0.5 on 2026-06-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_userprofile_requires_password_reset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('message', models.TextField(default='We are currently performing system maintenance. Please check back shortly. We apologize for the inconvenience.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Maintenance Mode',
                'verbose_name_plural': 'Maintenance Mode',
            },
        ),
    ]
