# Generated by Django 6.0.5 on 2026-06-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0005_maintenancemode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraudlog',
            name='action',
            field=models.CharField(choices=[('deposit_verified', 'Deposit Verified'), ('deposit_rejected', 'Deposit Rejected'), ('account_frozen', 'Account Frozen'), ('account_unfrozen', 'Account Unfrozen'), ('account_banned', 'Account Banned'), ('account_unbanned', 'Account Unbanned'), ('investment_cancelled', 'Investment Cancelled'), ('balance_adjusted', 'Balance Adjusted'), ('withdrawal_approved', 'Withdrawal Approved'), ('withdrawal_rejected', 'Withdrawal Rejected')], max_length=30),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='code',
            field=models.CharField(max_length=200),
        ),
    ]
